artifact_uri: runs\mlflow/1/015b1f5c49d842f195e1edd8bab3ce13/artifacts
end_time: 1704694269292
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 015b1f5c49d842f195e1edd8bab3ce13
run_name: train
run_uuid: 015b1f5c49d842f195e1edd8bab3ce13
source_name: ''
source_type: 4
source_version: ''
start_time: 1704693973628
status: 3
tags: []
user_id: prathamesh.s
